[book]
title = "AI & Machine Learning Lecture Notes"
authors = ["Cateds"]
language = "zh_cn"
src = "lectures"

[preprocessor.katex]
after = ["links"]

[output.html]
git-repository-url = "https://github.com/Cateds/AI-MachineLearning.md"
